version: "3"
services:

  backend:
    image: plone/plone-backend:6.1
    restart: always
    environment:
        ADDONS: "plone.app.z3cform"
        DEVELOP: "/app/src/plone.app.multilingual /app/src/collective.translators"
    ports:
    - "8080:8080"
    volumes:
      - data:/data
      - ./src:/app/src

volumes:
  data: {}

